name: Build release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Build application
      run: bun run build
    - name: Rename dist folder to the current tag
      run: mv dist ${{ github.ref_name }}
    - name: Zip application
      run: zip -r build.zip ${{ github.ref_name }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build.zip